apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: core-lab-wildcard
  namespace: traefik
spec:
  secretName: core-lab-wildcard-tls
  issuerRef:
    name: le-dns-porkbun
    kind: ClusterIssuer
  commonName: "*.core.lab.2bit.name"
  dnsNames:
    - "*.core.lab.2bit.name"
    - "core.lab.2bit.name"
